version: "3.7"
services:
  pulsar:
    image: apachepulsar/pulsar:2.6.0
    command: bin/pulsar standalone
    hostname: pulsar
    ports:
      - "7080:8080"
      - "6650:6650"
      - "8081:8081"
    restart: unless-stopped
    volumes:
      - "pulsar_data:/pulsar/data"
#    volumes:
#      - "./data/:/pulsar/data"
  dashboard:
    image: apachepulsar/pulsar-manager:v0.2.0
    ports:
      - "9527:9527"
      - "7750:7750"
    depends_on:
      - pulsar
    links:
      - pulsar
#    volumes:
###      - "./conf:/pulsar-manager/pulsar-manager/"
#      - "./application.properties:/pulsar-manager/pulsar-manager/application.properties"
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties

volumes:
  pulsar_data:
    driver: local